name = "gql-api"
main = "./src/index.ts"
# compatibility_date = "2024-09-23"
compatibility_date = "2025-02-16"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
NODE_VERSION = "22.14.0"
GQL_DEPTH_LIMIT = 4

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "HYPERDRIVE_ID"
